propel help:
	vendor/bin/propel

propel build:
	vendor/bin/propel sql:build

propel model:
	vendor/bin/propel sql:insert

propel config:
	vendor/bin/propel config:convert

propel build model:
	vendor/bin/propel model:build