version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: candidates/Dockerfile
    container_name: microservices-app
    restart: always
    working_dir: /www
    volumes:      
      - ./www:/www      

  nginx:
    image: nginx:1.19-alpine
    container_name: microservices-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:       
      - ./www:/www      
      - ./logs/nginx:/var/log/nginx/      

    networks:
      - internal
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./www:/www      
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge 